-- EN: A catalogue number per lot, shown as "Lot 001" (the frontend's lotNumber). Existing lots are
--     numbered in the order they were created; new ones take the next number from the identity.
-- VI: Mỗi lô một số thứ tự trong danh mục, hiển thị như "Lot 001" (lotNumber phía frontend). Các lô đã có
--     được đánh số theo thứ tự tạo; lô mới lấy số kế tiếp từ identity.

ALTER TABLE auctions ADD COLUMN lot_number BIGINT;

UPDATE auctions a
   SET lot_number = numbered.n
  FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) AS n FROM auctions) AS numbered
 WHERE a.id = numbered.id;

ALTER TABLE auctions ALTER COLUMN lot_number SET NOT NULL;

DO $$
DECLARE
    next_number BIGINT;
BEGIN
    SELECT coalesce(max(lot_number), 0) + 1 INTO next_number FROM auctions;
    EXECUTE format(
        'ALTER TABLE auctions ALTER COLUMN lot_number ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
        next_number);
END $$;

ALTER TABLE auctions ADD CONSTRAINT ux_auctions_lot_number UNIQUE (lot_number);
